### PR TITLE
Extracted code for offline verifier

### PR DESCRIPTION
**Pull request by joosep-wm**
We created a verifier for the inclusion proofs that works separately from the VDS service code. Because the verifier could not include all the dependencies from the main package, we extracted verification related code to independent packages. Then we could included these packages and create the verifier.

### CODE REVIEW

**Comment by aeijdenberg** [comment]
Hi @joosep-wm , thanks for sending through.

If I understand correctly, this doesn't introduce new functionality - rather it's moving sections of code into a separate package.

I'd like to understand more deeply the reason for doing so... Is that to reduce the number of Go packages that need to be installed in order to just use that code?

Is it just the number of packages, or is it the resulting binary size, or are certain packages causing problems?

e.g. if for example, the boltdb implementation for storage was dragging in a bunch of things that were starting to cause slow compile times, then I wonder perhaps if it might be better to move that out of this package, rather than move the core Merkle tree code out?

**Comment by jvsteiner** [comment]
@aeijdenberg - specifically, we are using gopherjs to generate javascript code to verify proofs that can run in the clients browser.  Gopherjs won't compile if boltdb is imported anywhere downstream. While this is our specific barrier, we thought it might be generally useful to break out verification functionality into a sub-package so it could be imported and namespaced specifically.

**Comment by aeijdenberg** [comment]
Thanks for the context @jvsteiner - I'm going to have a bit of a play with GopherJS - I hadn't seen it before.

Btw, not sure if you knew but I did also do a Javascript version of the client library (though that was originally for the hosted version, so maybe a little out of date now): https://github.com/continusec/javascript-client

**Comment by jvsteiner** [comment]
Hi Adam - thanks for pointing out the js library - we'll take a look, but we anyway will still need use gopher to generate verification code for a while, due to various reasons. We don't intend to ship any code generated with it, btw - but it's quite useful to keep client code in sync with server side changes during development.

**Comment by aeijdenberg** [comment]
Thanks @jvsteiner .  I agree we should support this use case.  But I don't like pulling it out into a vaguely named `utils` package - I think we can do better than that, so I'm not keen to merge this PR as is.

I'd rather find a better way to reorganize the packages so that `gopherjs` can do it's thing nicely, but ideally keep all of the code that doesn't depend on other packages, in it's own package.

While iterating on this library I'd originally spilt it up a bit differently, and ran into a number of difficulties with circular dependencies (which Go doesn't support), which is one of the reasons I moved it all into this one package.

I think it should be straightforward to split the Bolt packages out - and I think after you commit your other PR for Badger we can do the same there, and there might be a nice way to do so with some of the other dependencies.

Can you share the command or config you are using as a test-case for GopherJS and I'd be happy to iterate a little on that?

**Comment by aeijdenberg** [comment]
@joosep-wm @jvsteiner  I did some experimenting with moving files around and doing some renames to reduce stutter.  How does this branch look: <https://github.com/continusec/verifiabledatastructures/tree/refactor>

It moves everything down at least one level, and keeps all of the interfaces inside of the `verifiable` package, but pushes all the implementations outside.

I note that it does still pull in more `grpc` stuff than I'd prefer but at least removes dependencies on `bolt`. Let me know if this would work for the `gopherjs` case?

**Comment by joosep-wm** [comment]
@aeijdenberg I tried out the `refactor` branch. It works nicely with the gopherjs. I agree that this structure makes more sense what I did initially.

**Comment by aeijdenberg** [comment]
Thanks @joosep-wm . I went ahead and merged the `refactor` branch, and I'll close this PR out.

Let me know if there are other changes needed to help support this use-case.

**Pull request closed without merging**
